### ISSUE TITLE
Readme: indicate $TEXMFLOCAL for Native TeX Live too

### ISSUE THREAD

**Issue by copycat-killer** [sebschub/FontPro#61]
`$TEXMFLOCAL` is not always defined, so in the [first point](https://github.com/sebschub/FontPro/blob/master/README.md#installing) of *Installing* section in the readme, I suggest to add that the install path for Native TeX Live is:

```shell
/usr/local/texlive/texmf-local/
```

**Comment by sebschub** [comment]
If `$TEXMFLOCAL` was not defined, where would TeXlive know that it has to search `/usr/local/texlive/texmf-local/`?

**Comment by copycat-killer** [comment]
Frankly I don't know how TeX Live works, but in my case, `echo $TEXMFLOCAL` shows a blank line.

All I wanted to say is that you could specify for further clarity that in case Native Tex Live is being used, the above path is the right one.

**Comment by sebschub** [comment]
`TEXMFLOCAL` is not a normal environment variable, you get its value with `kpsewhich -expand-var='$TEXMFLOCAL'`. Thus, I would expect that it also works for you. Actually, I think I should even remove the example because just using the install script with TEXMFLOCAL should do the right thing. Only if this fails or one really wants to use another folder (for user-based installation), one has to give a folder.

**Comment by copycat-killer** [comment]
> Only if this fails or one really wants to use another folder (for user-based installation)

I believe this is my use case, that is a local installation.

**Comment by sebschub** [comment]
OK, I still need to understand your case. You installed TeXlive manually, right? As far as I know, in TeXlive, there are by default three folders which are searched for packages: `TEXMFDIST`, `TEXMFLOCAL` and `TEXMFHOME` (see https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-110002.3). On my system, they look like
```
sebschub@linux-eiht ~ $ kpsewhich -expand-var='$TEXMFDIST'
/usr/share/texmf
sebschub@linux-eiht ~ $ kpsewhich -expand-var='$TEXMFLOCAL'
/usr/local/share/texmf
sebschub@linux-eiht ~ $ kpsewhich -expand-var='$TEXMFHOME'
/home/sebschub/texmf
```
These are the only reasonable choices unless the user defines non-standard additional folders. Actually, only `TEXMFLOCAL` and `TEXMFHOME` should be used because `TEXMFDIST` is not meant for manual adjustments. The current default of my scripts is the system-wide `TEXMFLOCAL`. Here the installing user needs to get root permissions. So on you system, I would expect `TEXMFLOCAL` refers to `/usr/local/texlive/texmf-local/`. Thus, `./scripts/install` and `./scripts/install /usr/local/texlive/texmf-local/` are equivalent. Thus, I see no point to mention `/usr/local/texlive/texmf-local/`. If `TEXMFLOCAL` does not point to `/usr/local/texlive/texmf-local/` then an installation in `/usr/local/texlive/texmf-local/` would not work (again unless the user defined custom TeXlive folders which is then known to user user of course). So the same argument is true for my current example `/usr/local/share/texmf` which also represent `TEXMFLOCAL`. Thus, I should use another example. Obviously, `TEXMFHOME` is the only real choice. A user would use `TEXMFHOME` if (s)he could not get root permissions.
